# Site settings
title: Coming soon
email: s.moia@bcbl.eu
description: Multi-session CVR variability within functional networks
baseurl: "/cvr-variability-within-fn" # the subpath of your site, e.g. /blog
url: "https://smoia.github.io" # the base hostname & protocol for your site

# Homepage tiles
tiles-source: posts # accepts "posts" or "pages"
tiles-count: 3

# Misc settings
featured-image-source:

# Social settings
500px_url:
facebook_url:
github_url: https://smoia.github.io
gitlab_url:
googleplus_url:
instagram_url:
linkedin_url:
pinterest_url:
slack_url:
twitter_url: https://twitter.com/SteMoia

# Build settings
markdown: kramdown
